version: '3.1'

services:

  jenkins:
       image: wimmelsoft/jenkins:1.0
       deploy:
         restart_policy:
           condition: on-failure
           delay: 5s
           max_attempts: 3
           window: 120s    
       ports:
         - 8090:8080
         - 50000:50000  
       networks:
         - wimmelsoft
       volumes:
         - ./jenkins/data:/var/jenkins_home

  db-bitbucket:
       image: postgres:latest
       deploy:
         restart_policy:
            condition: on-failure
            delay: 5s
            max_attempts: 3
            window: 120s  
       environment:
          POSTGRES_USER: bitbucket
          POSTGRES_PASSWORD: b1tbucket
          POSTGRES_DB: bitbucket
       networks:
         - wimmelsoft
       ports:
         - 5432:5432
       volumes:
         - ./postgres/database:/var/lib/postgresql

  postgres:
    image: postgres:latest
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      POSTGRES_USER: generic
      POSTGRES_PASSWORD: p0stgr3s
      POSTGRES_DB: generic
    networks:
      - wimmelsoft
    ports:
      - 5433:5432
    volumes:
      - ./postgres/generic:/var/lib/postgresql

  bitbucket:
       image: atlassian/bitbucket-server:6.3.5-jdk11
       deploy:
         restart_policy:
           condition: on-failure
           delay: 5s
           max_attempts: 3
           window: 120s
       environment:
         JDBC_DRIVER: org.postgresql.Driver
         JDBC_USER: bitbucket
         JDBC_PASSWORD: b1tbucket
         JDBC_URL: jdbc:postgresql://db-bitbucket:5432/bitbucket
       ports:
         - 7990:7990
         - 7999:7999
       volumes:
         - bitbucketVolume:/var/atlassian/application-data/bitbucket
       networks:
         - wimmelsoft
       depends_on:
         - db-bitbucket

  adminer:
       image: adminer
       deploy:
         restart_policy:
           condition: on-failure
           delay: 5s
           max_attempts: 3
           window: 120s
       ports:
         - 8900:8080
       networks:
         - wimmelsoft        
        
volumes:
  bitbucketVolume:

networks:
  wimmelsoft:
    driver: overlay
