FROM atlassian/bitbucket-server:6.3.5-jdk11
EXPOSE 7990
EXPOSE 7999
ENV JDBC_DRIVER=org.postgresql.Driver
ENV JDBC_USER=bitbucket
ENV JDBC_PASSWORD=b1tbucket
ENV JDBC_URL=jdbc:postgresql://db:5432/bitbucket

